# Golden / characterization test for the simInit() `.inputObjects` rework.
#
# fixtures/inputObjects-golden.rds was generated by running ioGoldenSnapshot()
# (see helper-inputObjectsGolden.R) on the pre-rework base commit, before `.inputObjects`
# were moved onto the event queue. This test re-runs the identical scenarios on the current
# code and asserts a byte-for-byte identical normalized snapshot -- i.e., that the rework
# did not change observable simInit() behaviour (objects created, the post-simInit event
# queue, which modules' `.inputObjects` completed and in what set, user-supplied names, and
# loaded modules). See helper-inputObjectsGolden.R for how to regenerate the fixture.

test_that("simInit .inputObjects behaviour matches the pre-rework baseline", {
  skip_on_cran()
  fixture <- testthat::test_path("fixtures", "inputObjects-golden.rds")
  skip_if_not(file.exists(fixture), "golden fixture not present")

  golden <- readRDS(fixture)
  d <- withr::local_tempdir()
  current <- ioGoldenSnapshot(d)

  expect_equal(names(current), names(golden))
  for (scenario in names(golden)) {
    expect_equal(current[[scenario]], golden[[scenario]],
                 info = paste0("scenario '", scenario, "' differs from the pre-rework baseline"))
  }
})
