on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, nosuggests ${{ matrix.config.nosuggests }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   nosuggests: false, r: 'release'}
          - {os: windows-latest, nosuggests: false, r: 'devel', http-user-agent: 'release'}
          - {os: windows-latest, nosuggests: false, r: 'release'}
          - {os: windows-latest, nosuggests: true,  r: 'release'}
          - {os: windows-latest, nosuggests: false, r: 'oldrel-1'}
          - {os: windows-latest, nosuggests: false, r: 'oldrel-2'}
          - {os: ubuntu-latest,  nosuggests: false, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  nosuggests: false, r: 'release'}
          - {os: ubuntu-latest,  nosuggests: true,  r: 'release'}
          - {os: ubuntu-latest,  nosuggests: false, r: 'oldrel-1'}
          - {os: ubuntu-latest,  nosuggests: false, r: 'oldrel-2'}

    env:
      _R_CHECK_DEPENDS_ONLY_: ${{ matrix.config.nosuggests }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      SPADES_USE_REQUIRE: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: PredictiveEcology/actions/install-spatial-deps@v0.2

      - uses: r-lib/actions/setup-r@v2
        with:
          http-user-agent: ${{ matrix.config.http-user-agent }}
          Ncpus: 2
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            PredictiveEcology/reproducible@AI
            fastshp=?ignore
            NLMR=?ignore
          needs: check

      - name: Install additional package dependencies
        run: |
          pak::pkg_install("ropensci/NLMR")
          pak::pkg_install("s-u/fastshp")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'
